### PR TITLE
Add initial content to the website

### PR DESCRIPTION
**Pull request by eashwar**
This adds the content specified in the Google Doc shared by Amanda, except for the sponsor page. The styling is very basic but this PR is just to get the content on the site and (somewhat) organized

### CODE REVIEW

**Comment by hal7df** [comment]
Doesn't the competition page also need a `.md` file?

**Comment by eashwar** [comment]
just out of laziness, i've made both about and competition html files in the root directory (about's md is also gone)

**Comment by hal7df** [comment]
Ah OK

**Review by hal7df — APPROVED** [review]
:+1:

**Pull request merged**
